### ISSUE TITLE
support for suffixes

### ISSUE THREAD

**Issue by fc-io** [perkinsben/obs_tools#1]
Hi! 

Very nice of you to make this script. I was looking to build something myself, but now I'm at least gonna wait for 3d party plugin support. :D

If you have time, and find it a suitable addition, then I'd like to see support for basic suffixes.

Example:

With a file names `Apple`

```
Text with apples. 
```

Would be formatted to:

```
Text with [[apple|apples]]. 
```

Would be nice if this matching is non-specific and handles any word endings, and not just `s`. (To handle multiple languages out of the box.)

**Comment by perkinsben** [comment]
Unfortunately I'm not using a dictionary or language parsing, so there's no ability to intelligently identify suffixes correctly. The tool uses regular expressions only to identify matches, which allows the use of various languages/character sets, but does not attempt to make sense of the word/phrase being searched. Without proper dictionary parsing, I'd just be guessing at suffixes and may even identify false positives (like "his/hiss" or "miss/misses").

**Comment by fc-io** [comment]
Yeah, I do not want some kind of dictionary matching either. For my use case it would have worked fine with having it match on the first part of the word. False positives would not be a big deal for me, but maybe my workflow is a bit different.

Thank you anyway, code is nice and readable. I'll make do :).
