### ISSUE TITLE
Script optimisation

### ISSUE THREAD

**Issue by dxcore35** [perkinsben/obs_tools#12]
I have 7000 notes, and the script is running already 3 hours in my Macbook 12". It runs just one core on 98%...
It will be amazing if you can optimise speed a little bit... Add some subprocesses....

**Comment by perkinsben** [comment]
This sounds like something else is going on. Can you provide the command that you ran? And is there any output on the console?

Even with 7000 files, it shouldn't take long to process the files. I suspect it's stuck thrashing in a loop or something.

**Comment by dxcore35** [comment]
I'm running standard command: ```Python3 obs-linkr.py <path to my obsidian vault root>```
There was no output in terminal.

- After 5 hours I stoped the script
- I also ensured that all notes are have unique names

Any good part of the script where I can add ```print``` for debuging?

**Comment by perkinsben** [comment]
There are some spots where I have commented lines useful for debugging. Start with uncommenting line 114 and see if it points to a file that is causing trouble.

Have you ever been able to see this script work, or is this your first time running it? You don't happen to have a massive block of text in your clipboard, do you?

If you're running the script with no arguments (other than path to vault), the script isn't even reading files, just looking at the filenames in your vault and attempting to link those inside the text from your clipboard.

**Comment by dxcore35** [comment]
Now I'm running the script... the catching of all notes names, was only in blink of the eye...
Now I'm getting update list of:

linked xy1
linked xy2
....

It is still running.

But the rate of update of the new item is around 1 second.

---

I forgot to mention :D that there are thousands of words to be linked....
I have massive block of text in clipboard :D

**Comment by perkinsben** [comment]
Ah, OK. Is the rate of display of the text 'linked xyz' consistently 1 second, or does it get slower? Could you try linking a smaller subset of your text to see if the size of the clipboard is the issue?

**Comment by dxcore35** [comment]
I tested smaller clipboard ... it was just blink of the eye and all files were linked in text.
So it looks like there is some problem with handling bigger texts. 
- the python is using just 60MB of my RAM

**Comment by dxcore35** [comment]
This is off topic:
- but now I'm seeing that it also replace the text in my headings...this is not quite desirable behavior
- I mean it is easy to fix but, still

**Comment by perkinsben** [comment]
You mean the text in '#### Header'? Yes, the tool doesn't differentiate between regular text and header text or other markdown.

The tool is more designed to work on paragraphs or a page or two of text. I'll do some testing on a larger vault with a large clipboard in the coming days.

You may want to try and break the clipboard text up into smaller chunks.

**Comment by dxcore35** [comment]
I can split the text into smaller files, but it will be 13.000 files....
Then the next problem will be how I can execute the script for each file... 

Do you have some ideas?

- I can loop all files in vault and then call your script and paste the text into file and go to next...

**Comment by perkinsben** [comment]
Yes, I would do something like that. The pyperclip library that is used in the script for working with the clipboard makes getting and setting your text easy.

**Comment by dxcore35** [comment]
But I can save the text directly into the file just in Python. Is the `pyperclip` use-full only when handling clipboard?

**Comment by perkinsben** [comment]
Yes, just for clipboard. You'll probably want to do something like:

```
for each file:
  open the file
  read content to clipboard
  run obs-linkr
  write the linked clipboard text back out to the file
```

If you're doing something like this, I'd recommend you use a copy/backup of your vault, rather than the actual files, just in case something goes wrong with writing to the files.

**Comment by dxcore35** [comment]
Ok it is done... it is blazing fast!

It several minuets to:
- read around: 13.000 files
- create around: 420.000 [[links]] !
- write around: 13.000 files

Your script is amazing. I really appreciate your work!
It save us tons and tons of man hours 👍

**Comment by perkinsben** [comment]
Wow, those are impressive numbers! Glad I could help.
