### ISSUE TITLE
python module dependency

### ISSUE THREAD

**Issue by ksandvik** [perkinsben/obs_tools#14]
Looks like the latest python frontmatter can't use the latest pyyml, so maybe the README instructions should show the exact versions at this point of time to get this working properly at initial install.

**Comment by perkinsben** [comment]
Thanks for the heads up on this. I'll work on this over the next couple of
days.

**Comment by ksandvik** [comment]
I tried to install pyyml 5.1, and uninstalling various packages, but always end up with 
```bash
 ~> python3 obs-linkr.py /Volumes/Work/Obsidian-Tib-workspace/ -r
Traceback (most recent call last):
  File "obs-linkr.py", line 2, in <module>
    import frontmatter
ModuleNotFoundError: No module named 'frontmatter'
```
And yes, latest frontmatter is installed.

**Comment by perkinsben** [comment]
Are you sure you didn't install 'frontmatter' as opposed to 'python-frontmatter'? I just updated pyyaml and python-frontmatter to the latest and I'm not having issues. I remember when I introduced frontmatter parsing, I had unresolvable issues with the plain 'frontmatter' library, so went with 'python-frontmatter'.

Let me know if the library switch resolves your issue, but I'm happy to put the specific versions in the documentation also.

**Comment by ksandvik** [comment]
```
forward_linker (master) ~>pip3 install pyperclip pyyaml python-frontmatter
Collecting pyperclip
  Downloading pyperclip-1.8.2.tar.gz (20 kB)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.9/site-packages (5.1)
Requirement already satisfied: python-frontmatter in /usr/local/lib/python3.9/site-packages (1.0.0)
Building wheels for collected packages: pyperclip
  Building wheel for pyperclip (setup.py) ... done
  Created wheel for pyperclip: filename=pyperclip-1.8.2-py3-none-any.whl size=11107 sha256=4f5e6c4fc5b006dd9b36209ffbd14e1b908d302c878d7bc40d4931250ea9c1cc
  Stored in directory: /Users/ksandvik/Library/Caches/pip/wheels/0c/09/9e/49e21a6840ef7955b06d47394afef0058f0378c0914e48b8b8
Successfully built pyperclip
Installing collected packages: pyperclip
Successfully installed pyperclip-1.8.2
/Users/ksandvik/code/github/obs_tools/forward_linker
forward_linker (master) ~> python3 obs-linkr.py /Volumes/Work/Obsidian-Tib-workspace/ -r
Traceback (most recent call last):
  File "obs-linkr.py", line 2, in <module>
    import frontmatter
ModuleNotFoundError: No module named 'frontmatter'
```
I'm running one of the later pythons:
```
forward_linker (master) ~> python3 --version
Python 3.8.2
```

**Comment by perkinsben** [comment]
I've got a couple things you might try:

1) Revert to older versions of the dependencies and see if that resolves it:

```
pip3 uninstall pyperclip pyyaml python-frontmatter
pip3 install -Iv pyperclip==1.8.0 pyyaml==5.1 python-frontmatter==0.5.0
```

2) Edit obs-linkr.py and swap lines 2 and 3 to look like the following:

```
import pyperclip
import frontmatter
```

If the error fails on pyperclip instead, it could be environment-related. It's interesting that pip is storing libraries at /usr/local/lib/python3.9/, but python is reporting version 3.8.2. Perhaps those aren't pointing at the same library location.

**Comment by ksandvik** [comment]
I found the issue, my brew Mac setup had two python3 versions, and pip/pip3 was pointing at the python3.9 while the default python3 was python3.8.2. Another side effect of the unfortunate way the pip system and python versions were designed. I relinked python3 on my Mac to 3.9 and now it finds the installed frontmatter. Feel free to close this one.
