### ISSUE TITLE
combine obs-unlinkr.py code into obs-linkr.py for stripping and re-creating the links

### ISSUE THREAD

**Issue by ksandvik** [perkinsben/obs_tools#17]
I wrote a bash script to first run obs-unlinkr.py and then obs-linkr.py as in 99 of 100 cases the intent for existing use is to update the contents. And for that clearing the markup in the clipboard is the first phase.

Could you combine this code into obs-linkr.py with a special flag so it's opt-in? This way there's only one case of launching the (heavy) python runtime rather than twice, to save cycles?

**Comment by perkinsben** [comment]
OK, so to be clear you'd like to see the unlinkr code merged into the linkr script, then a new command-line (or similar) option to clear the clipboard contents of internal links before executing the linking?

**Comment by ksandvik** [comment]
Yes, a one-pass of obs-linkr.py where the first pass is to take the clipboard contents and strip out the existing markup, and second pass is to use the created text buffer variable for the actual new markup. This way there's no need to launch the python runtime twice.

It's OK if this is behind a special flag. You could also think of combining the obs-unlinkr.pr and obs-linkr.py to one single executable were the stripping of markup is handled with flags.

**Comment by perkinsben** [comment]
This should be resolved with the latest commit. Use the -u option when calling obs-linkr to unlink clipboard text before linking.

**Comment by perkinsben** [comment]
Sorry, forgot to push - it's there now.

**Comment by ksandvik** [comment]
Thx, will test.

**Comment by Mollie107** [comment]
Good Advice!
