### ISSUE TITLE
Ignore Obsidian .trash folder

### ISSUE THREAD

**Issue by Raagaception** [perkinsben/obs_tools#19]
Can you please update the script to ignore any ``.md`` files inside the Obsidian .trash folder? Currently it picks up aliases from deleted files too. 
![image](https://user-images.githubusercontent.com/72780589/120767028-6f3c5f00-c538-11eb-8866-c70a0b5e7f3a.png)

**Comment by perkinsben** [comment]
I'll look at it this weekend. What do you think about just ignoring any folder starting with a dot?
