### ISSUE TITLE
Search and replace orders

### ISSUE THREAD

**Issue by trungng2006** [perkinsben/obs_tools#2]
Thank you for sharing this. 
When i use this tool, sometimes it would shows that the word have been processed many times
Such as if i have keywords on team, learning and team learning episode:
1. [[Team [[Learning|learning]] episode|team [[Learning|learning]] episode]] instead of [[Team learning episode|team learning episode]]
2. [[Team [[Learning|learning]] episode|Learning Episode]] instead of [[Team learning episode|Learning Episode]]
So i would suggest to prioritized long words over short words, then if the words is between the double bracket already then do not replace

**Comment by perkinsben** [comment]
I noticed this myself and made some changes to the script (improved regular expression matching). Can you update to the newest version of the script and let me know if you still have the issue?

**Comment by trungng2006** [comment]
I have just coppied the code and try again. I have the same results.
I uploaded both the text MD file (showing input and result) and  the yml file here to help replicate.
https://www.dropbox.com/sh/zi61y906rk405w7/AAAB3hdQvrJTpOPaHoCo9wUla?dl=0

**Comment by perkinsben** [comment]
Please try the latest code update and see if that resolves your issue.

**Comment by trungng2006** [comment]
This fixed the problem above, but only half of the document got replace.
original: https://www.dropbox.com/s/eyxk58jg0ias6yq/original.txt?dl=0
results: https://www.dropbox.com/s/8fkrcp4etuvgfec/result.txt?dl=0

**Comment by trungng2006** [comment]
if you copy the left-over half to run again. It will also replace half of that part

**Comment by perkinsben** [comment]
I didn't change any of the code related to the document linking. I only added code to clean up the invalid links. Did you have this 'linking half the document' problem with the original code? I was able to run your document against my vault and the entire thing was linked successfully. Any errors shown on the console when running?

**Comment by trungng2006** [comment]
no, the original code ran for the whole file. 

For the new code, after it link, then scrub,before saying "linked text copied to clip board, it print the whole article on command window again. This behavior did not exhibit on the original code.

**Comment by perkinsben** [comment]
Yeah, I'm seeing the behavior now after replicating your vault. Give me some time with it.

**Comment by trungng2006** [comment]
Thank you!

**Comment by perkinsben** [comment]
I reverted the master branch and created a separate branch (issue2) to resolve this so that others aren't affected.

**Comment by trungng2006** [comment]
Okie!

**Comment by perkinsben** [comment]
@trungng2006 Please try the version here: https://github.com/perkinsben/obs_tools/blob/issue2/forward_linker/obs-linkr.py

**Comment by trungng2006** [comment]
worked perfectly!. 
(even faster i think, maybe you can put time count to test the efficiency (suggestion only))

**Comment by trungng2006** [comment]
Thank you so much!

**Comment by perkinsben** [comment]
No problem. Side note: I noticed that in your aliases.yml, you included aliases that are just variations on the casing of certain letters. You shouldn't need to do that - the tool will catch those and preserve the original text/casing. The aliases that are variations of text (plurals, suffixes, etc.) however are good.

**Comment by trungng2006** [comment]
wow, even better!
