### ISSUE TITLE
-w wikiflag for paragraph

### ISSUE THREAD

**Issue by trungng2006** [perkinsben/obs_tools#4]
May I ask if it is possible to implement -w for paragraph base also? (currently as I understand the implementation is on page/note based)
Use case: For user who will do note refactoring after running this script.

**Comment by perkinsben** [comment]
Can you explain a bit more? All of the text on the clipboard is considered when linking, but there is no concept of identifying paragraphs...

**Comment by trungng2006** [comment]
Sorry, maybe the term paragraph is not correct. maybe the term should be text block/ text line?

in the pic, team learning is linked only once each block.
![image](https://user-images.githubusercontent.com/71961905/97127581-fb9dcc80-1774-11eb-94ce-cb8390cd760e.png)

(the *** is just to highlight for illustration)

**Comment by perkinsben** [comment]
I think this is a good feature. I'll work on this.

**Comment by trungng2006** [comment]
Thank you!
