### ISSUE TITLE
Option to use only YML as dictionary 

### ISSUE THREAD

**Issue by trungng2006** [perkinsben/obs_tools#5]
Could you please add an option to only use aliases.yml as the dictionary (without using the note title in the vault).

**Comment by perkinsben** [comment]
This can be accomplished by pointing at a vault that contains an aliases.yml, but no .md files (eg. there are no note titles to link, only aliases).

aliases.yml:
```
Hello:
- hi

Earth:
- world
```

clipboard text:
``Hello there world, how are you?``

command:
``python obs-linkr.py c:\empty-vault``

output:
``Hello there [[Earth|world]], how are you?``

Note that 'Hello' was not linked, even though the aliases.yml defines it as a note title. If Hello.md is not present, it will not be linked, but its aliases will be.

**Comment by trungng2006** [comment]
Yeah, i should have thought of this, was too rigid in my thinking
Thank you for your patient
